.\"Created with GNOME Manpages Editor
.\"http://sourceforge.net/projects/gmanedit2

.\"Replace <program> with the program name, x with the Section Number
.TH LIBRE-IMPUESTOS 1 "Martes 05-11-2013" "" "MANUAL DE LIBRE-IMPUESTOS"

.SH NAME
libre-impuestos \- Apliación escritorio para recaudar impuestos de Bolivia

.SH SYNOPSIS
.B libre-impuestos

.SH DESCRIPTION
Este manual de usuario, explica la funcionalidad de la aplicación \fBlibre-impuestos\fP.

.SH OPTIONS
.IP \fB\-OPTION\fP
Sin opciones por el momento...

.SH AUTHOR
Writen by Henry Castro <hcvcastro@gmail.com>.

.SH REPORTING BUGS
Report bugs to <hcvcastro@gmail.com>.
.
.SH COPYRIGHT
Copyright 2013 Free Software Foundation, Inc.
.br

This is free software; see the source for copying conditions.  There is NO  warranty;  not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.



